# Generated by Django 4.0.6 on 2025-04-15 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('direction', models.CharField(choices=[('IN', 'Въезд'), ('OUT', 'Выезд')], max_length=255, verbose_name='Направление')),
                ('type', models.CharField(choices=[('auto', 'Авто'), ('selfauto', 'Самовывоз'), ('selfout', 'Самовынос')], max_length=255, verbose_name='Тип')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер паспорта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер ТС')),
                ('vehicle_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель ТС')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expeditions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_expeditions', to='organizations.organization', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_expeditions', to='organizations.organization', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'экспедиция',
                'verbose_name_plural': 'экспедиции',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('unit_of_measurement', models.CharField(blank=True, choices=[('шт', 'Штуки'), ('кг', 'Килограммы'), ('л', 'Литры'), ('м', 'Метры')], max_length=50, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'ТМЦ',
                'verbose_name_plural': 'ТМЦ',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('cargo_description', models.TextField(blank=True, null=True, verbose_name='Описание груза')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='expeditions.expedition', verbose_name='Экспедиция')),
            ],
            options={
                'verbose_name': 'накладная',
                'verbose_name_plural': 'накладные',
            },
        ),
        migrations.CreateModel(
            name='InvoiceGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_goods', to='expeditions.good', verbose_name='ТМЦ')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_goods', to='expeditions.invoice', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'ТМЦ в накладной',
                'verbose_name_plural': 'ТМЦ в накладных',
                'unique_together': {('invoice', 'good')},
            },
        ),
    ]
