# Generated by Django 4.0.6 on 2025-04-15 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkpoints', '0001_initial'),
        ('expeditions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('cancelled', 'Отклонено')], max_length=50, verbose_name='Статус')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подтверждения')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Подтверждено')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='expeditions.expedition', verbose_name='Экспедиция')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='checkpoints.zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'подтверждение',
                'verbose_name_plural': 'подтверждения',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
