@startuml Expedition Creation Process

title Процесс создания экспедиции

skinparam activityBorderColor black
skinparam activityBackgroundColor LightSkyBlue
skinparam arrowColor DarkBlue

|Логист|
start
:Авторизоваться в системе;
:Выбрать "Создать экспедицию";

|#AntiqueWhite|Фронтенд|
:Отобразить экран создания экспедиции (Шаг 1);

|Логист|
:Шаг 1: Выбрать основные параметры:
- Направление (въезд/выезд)
- Организация-отправитель
- Организация-получатель;

:Нажать "Далее";

|Фронтенд|
:Отобразить экран создания экспедиции (Шаг 2);

|Логист|
:Шаг 2: Заполнить дополнительные данные:
- Наименование экспедиции
- Тип (авто/самовывоз/самовынос);

:Заполнить данные водителя/представителя:
- ФИО
- Номер паспорта
- Номер телефона;

if (Тип = Авто или Самовывоз?) then (да)
  :Заполнить данные ТС:
  - Гос. номер
  - Модель;
else (нет)
endif

:Нажать "Далее";

|Фронтенд|
:Отобразить экран создания экспедиции (Шаг 3);

|Логист|
:Шаг 3: Управление накладными;

repeat
  :Нажать "Добавить накладную";
  :Заполнить данные накладной:
  - Номер
  - Описание груза;
  
  repeat
    :Выбрать товар из списка
    существующих товаров;
    :Указать количество;
  repeat while (Добавить еще товар?) is (да)
  ->нет;
repeat while (Добавить еще накладную?) is (да)
->нет;

:Нажать "Сохранить";

|Фронтенд|
:Сформировать запрос на создание экспедиции;

|#LightYellow|Бэкенд API|
:Получить запрос на создание экспедиции;
:Валидировать данные;

if (Данные валидны?) then (да)
  :Создать экспедицию;
  :Создать накладные;
  :Создать связи товаров с накладными;
  :Сохранить дату начала экспедиции;
  :Вернуть подтверждение создания экспедиции;
  
  |Фронтенд|
  :Отобразить сообщение об успешном создании;
  :Перенаправить на список экспедиций;
else (нет)
  :Вернуть ошибки валидации;
  
  |Фронтенд|
  :Отобразить ошибки;
  :Прервать процесс создания экспедиции;
endif

|Логист|
:Увидеть результат создания экспедиции;

stop

@enduml 